<?php

namespace ContainerNHymhJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_54ak1dAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.54ak1dA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'budget' => ['privates', '.errored..service_locator.54ak1dA.App\\Entity\\management\\Budget', NULL, 'Cannot autowire service ".service_locator.54ak1dA": it needs an instance of "App\\Entity\\management\\Budget" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'budget' => 'App\\Entity\\management\\Budget',
            'entityManager' => '?',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.54ak1dA'])) {
            return $container->privates['.service_locator.54ak1dA'];
        }

        return $container->privates['.service_locator.54ak1dA'] = $instance;
    }
}
