<?php

namespace ContainerNHymhJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZY4Nk7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zY4Nk7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transaction' => ['privates', '.errored..service_locator.zY4Nk7F.App\\Entity\\management\\Transaction', NULL, 'Cannot autowire service ".service_locator.zY4Nk7F": it needs an instance of "App\\Entity\\management\\Transaction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'transaction' => 'App\\Entity\\management\\Transaction',
        ]);

        if (isset($container->privates['.service_locator.zY4Nk7F'])) {
            return $container->privates['.service_locator.zY4Nk7F'];
        }

        return $container->privates['.service_locator.zY4Nk7F'] = $instance;
    }
}
