<?php

namespace ContainerNHymhJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HHItWJgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HHItWJg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateur' => ['privates', '.errored..service_locator.HHItWJg.App\\Entity\\user\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.HHItWJg": it needs an instance of "App\\Entity\\user\\Utilisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'utilisateur' => 'App\\Entity\\user\\Utilisateur',
        ]);

        if (isset($container->privates['.service_locator.HHItWJg'])) {
            return $container->privates['.service_locator.HHItWJg'];
        }

        return $container->privates['.service_locator.HHItWJg'] = $instance;
    }
}
