<?php

namespace ContainerNHymhJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecuteRecurringTransactionsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ExecuteRecurringTransactionsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\ExecuteRecurringTransactionsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:execute-recurring-transactions', [], 'Execute all due recurring transactions', false, #[\Closure(name: 'App\\Command\\ExecuteRecurringTransactionsCommand')] fn (): \App\Command\ExecuteRecurringTransactionsCommand => ($container->privates['App\\Command\\ExecuteRecurringTransactionsCommand'] ?? $container->load('getExecuteRecurringTransactionsCommandService')));
    }
}
