<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SVCjKIyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sVCjKIy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'wallet' => ['privates', '.errored..service_locator.sVCjKIy.App\\Entity\\Loan\\Wallet', NULL, 'Cannot autowire service ".service_locator.sVCjKIy": it needs an instance of "App\\Entity\\Loan\\Wallet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'wallet' => 'App\\Entity\\Loan\\Wallet',
        ]);

        if (isset($container->privates['.service_locator.sVCjKIy'])) {
            return $container->privates['.service_locator.sVCjKIy'];
        }

        return $container->privates['.service_locator.sVCjKIy'] = $instance;
    }
}
