<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P4WyGTKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P4WyGTK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'ticket' => ['privates', '.errored..service_locator.P4WyGTK.App\\Entity\\reclamation\\Ticket', NULL, 'Cannot autowire service ".service_locator.P4WyGTK": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".'],
            'ticketSlaCalculator' => ['privates', 'App\\Service\\TicketSlaCalculator', 'getTicketSlaCalculatorService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'ticket' => 'App\\Entity\\reclamation\\Ticket',
            'ticketSlaCalculator' => 'App\\Service\\TicketSlaCalculator',
        ]);

        if (isset($container->privates['.service_locator.P4WyGTK'])) {
            return $container->privates['.service_locator.P4WyGTK'];
        }

        return $container->privates['.service_locator.P4WyGTK'] = $instance;
    }
}
