<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EHAod2sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EHAod2s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EHAod2s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alertService' => ['privates', 'App\\Service\\MaturityAlertService', 'getMaturityAlertServiceService', true],
        ], [
            'alertService' => 'App\\Service\\MaturityAlertService',
        ]);
    }
}
