<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0V9MQQj.App\Entity\management\Categorie' shared service.
     *
     * @return \App\Entity\management\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0V9MQQj": it needs an instance of "App\\Entity\\management\\Categorie" but this type has been excluded in "config/services.yaml".');
    }
}
