<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContributionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ContributionController' shared autowired service.
     *
     * @return \App\Controller\ContributionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ContributionController.php';

        $container->services['App\\Controller\\ContributionController'] = $instance = new \App\Controller\ContributionController();

        $instance->setContainer(($container->privates['.service_locator.G._Ouo6'] ?? $container->load('get_ServiceLocator_G_Ouo6Service'))->withContext('App\\Controller\\ContributionController', $container));

        return $instance;
    }
}
