<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaturityAlertServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MaturityAlertService' shared autowired service.
     *
     * @return \App\Service\MaturityAlertService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MaturityAlertService.php';

        return $container->privates['App\\Service\\MaturityAlertService'] = new \App\Service\MaturityAlertService(($container->privates['App\\Repository\\InvestissementobligationRepository'] ?? $container->load('getInvestissementobligationRepositoryService')), ($container->privates['App\\Repository\\WalletRepository'] ?? $container->load('getWalletRepositoryService')));
    }
}
