<?php

namespace ContainerXvhFd14;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWalletService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sVCjKIy.App\Entity\Loan\Wallet' shared service.
     *
     * @return \App\Entity\Loan\Wallet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sVCjKIy": it needs an instance of "App\\Entity\\Loan\\Wallet" but this type has been excluded in "config/services.yaml".');
    }
}
