<?php

namespace ContainerUfTcM6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EScCwN8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EScCwN8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'likeRepository' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'em' => '?',
            'likeRepository' => 'App\\Repository\\LikeRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);

        if (isset($container->privates['.service_locator.EScCwN8'])) {
            return $container->privates['.service_locator.EScCwN8'];
        }

        return $container->privates['.service_locator.EScCwN8'] = $instance;
    }
}
