<?php

namespace ContainerUfTcM6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9sX7xqaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9sX7xqa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'feedback' => ['privates', '.errored..service_locator.9sX7xqa.App\\Entity\\user\\Feedback', NULL, 'Cannot autowire service ".service_locator.9sX7xqa": it needs an instance of "App\\Entity\\user\\Feedback" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'feedback' => 'App\\Entity\\user\\Feedback',
        ]);

        if (isset($container->privates['.service_locator.9sX7xqa'])) {
            return $container->privates['.service_locator.9sX7xqa'];
        }

        return $container->privates['.service_locator.9sX7xqa'] = $instance;
    }
}
