<?php

namespace ContainerUfTcM6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RLQgJ4xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RLQgJ4x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'investmentRepository' => ['privates', 'App\\Repository\\InvestissementobligationRepository', 'getInvestissementobligationRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ObligationRepository', 'getObligationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'investmentRepository' => 'App\\Repository\\InvestissementobligationRepository',
            'repository' => 'App\\Repository\\ObligationRepository',
        ]);

        if (isset($container->privates['.service_locator.RLQgJ4x'])) {
            return $container->privates['.service_locator.RLQgJ4x'];
        }

        return $container->privates['.service_locator.RLQgJ4x'] = $instance;
    }
}
