<?php

namespace ContainerUfTcM6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HHItWJg.App\Entity\user\Utilisateur' shared service.
     *
     * @return \App\Entity\user\Utilisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HHItWJg": it needs an instance of "App\\Entity\\user\\Utilisateur" but this type has been excluded in "config/services.yaml".');
    }
}
