<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ST7Es2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._sT7Es2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contributiongoal' => ['privates', '.errored..service_locator._sT7Es2.App\\Entity\\objective\\Contributiongoal', NULL, 'Cannot autowire service ".service_locator._sT7Es2": it needs an instance of "App\\Entity\\objective\\Contributiongoal" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contributiongoal' => 'App\\Entity\\objective\\Contributiongoal',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator._sT7Es2'])) {
            return $container->privates['.service_locator._sT7Es2'];
        }

        return $container->privates['.service_locator._sT7Es2'] = $instance;
    }
}
