<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P5RWJ9hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p5RWJ9h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'paginator' => '?',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);

        if (isset($container->privates['.service_locator.p5RWJ9h'])) {
            return $container->privates['.service_locator.p5RWJ9h'];
        }

        return $container->privates['.service_locator.p5RWJ9h'] = $instance;
    }
}
