<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ObqnxdMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.obqnxdM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'em' => '?',
            'httpClient' => '?',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);

        if (isset($container->privates['.service_locator.obqnxdM'])) {
            return $container->privates['.service_locator.obqnxdM'];
        }

        return $container->privates['.service_locator.obqnxdM'] = $instance;
    }
}
