<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHC_XQsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zHC.XQs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedbackRepository' => ['privates', 'App\\Repository\\FeedbackRepository', 'getFeedbackRepositoryService', true],
            'objectifRepository' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'feedbackRepository' => 'App\\Repository\\FeedbackRepository',
            'objectifRepository' => 'App\\Repository\\ObjectifRepository',
            'paginator' => '?',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);

        if (isset($container->privates['.service_locator.zHC.XQs'])) {
            return $container->privates['.service_locator.zHC.XQs'];
        }

        return $container->privates['.service_locator.zHC.XQs'] = $instance;
    }
}
