<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FZ6QIuYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fZ6QIuY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fZ6QIuY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'connection' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
            'repo' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
        ], [
            'connection' => '?',
            'repo' => 'App\\Repository\\ObjectifRepository',
        ]);
    }
}
