<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BnP0v7OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bnP0v7O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statisticService' => ['privates', 'App\\Bundle\\Statistic\\StatisticService', 'getStatisticServiceService', true],
        ], [
            'statisticService' => 'App\\Bundle\\Statistic\\StatisticService',
        ]);

        if (isset($container->privates['.service_locator.bnP0v7O'])) {
            return $container->privates['.service_locator.bnP0v7O'];
        }

        return $container->privates['.service_locator.bnP0v7O'] = $instance;
    }
}
