<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QLcBYgyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qLcBYgy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', '.errored.VxelfdV', NULL, 'Cannot determine controller argument for "App\\Controller\\managment\\TransactionController::step3()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\managment\\ValidatorInterface". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.qLcBYgy'])) {
            return $container->privates['.service_locator.qLcBYgy'];
        }

        return $container->privates['.service_locator.qLcBYgy'] = $instance;
    }
}
