<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LJw5_XoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LJw5.Xo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'faceService' => ['privates', 'App\\Service\\FacePlusPlusService', 'getFacePlusPlusServiceService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'faceService' => 'App\\Service\\FacePlusPlusService',
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.LJw5.Xo'])) {
            return $container->privates['.service_locator.LJw5.Xo'];
        }

        return $container->privates['.service_locator.LJw5.Xo'] = $instance;
    }
}
