<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2nOR4FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c2nOR4F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notificationService' => ['privates', 'App\\Service\\SimpleNotificationService', 'getSimpleNotificationServiceService', true],
            'obligationRepository' => ['privates', 'App\\Repository\\ObligationRepository', 'getObligationRepositoryService', true],
            'walletRepository' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService', true],
        ], [
            'entityManager' => '?',
            'notificationService' => 'App\\Service\\SimpleNotificationService',
            'obligationRepository' => 'App\\Repository\\ObligationRepository',
            'walletRepository' => 'App\\Repository\\WalletRepository',
        ]);

        if (isset($container->privates['.service_locator.c2nOR4F'])) {
            return $container->privates['.service_locator.c2nOR4F'];
        }

        return $container->privates['.service_locator.c2nOR4F'] = $instance;
    }
}
