<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinancialHealthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\advancedfeature\FinancialHealthController' shared autowired service.
     *
     * @return \App\Controller\advancedfeature\FinancialHealthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'advancedfeature'.\DIRECTORY_SEPARATOR.'FinancialHealthController.php';

        $container->services['App\\Controller\\advancedfeature\\FinancialHealthController'] = $instance = new \App\Controller\advancedfeature\FinancialHealthController();

        $instance->setContainer(($container->privates['.service_locator.BWRinXy'] ?? $container->load('get_ServiceLocator_BWRinXyService'))->withContext('App\\Controller\\advancedfeature\\FinancialHealthController', $container));

        return $instance;
    }
}
