<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicket2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EzKe0vE.App\Entity\reclamation\Ticket' shared service.
     *
     * @return \App\Entity\reclamation\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EzKe0vE": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".');
    }
}
