<?php

namespace ContainerRdzM3Wb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWalletControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Loan\WalletController' shared autowired service.
     *
     * @return \App\Controller\Loan\WalletController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Loan'.\DIRECTORY_SEPARATOR.'WalletController.php';

        $container->services['App\\Controller\\Loan\\WalletController'] = $instance = new \App\Controller\Loan\WalletController();

        $instance->setContainer(($container->privates['.service_locator.BWRinXy'] ?? $container->load('get_ServiceLocator_BWRinXyService'))->withContext('App\\Controller\\Loan\\WalletController', $container));

        return $instance;
    }
}
