<?php

namespace Proxies\__CG__\App\Entity\community;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\community\Post implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null, 16],
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateModification' => [parent::class, 'dateModification', null, 16],
        "\0".parent::class."\0".'idPost' => [parent::class, 'idPost', null, 16],
        "\0".parent::class."\0".'likes' => [parent::class, 'likes', null, 16],
        "\0".parent::class."\0".'nombreCommentaires' => [parent::class, 'nombreCommentaires', null, 16],
        "\0".parent::class."\0".'nombreLikes' => [parent::class, 'nombreLikes', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'typePost' => [parent::class, 'typePost', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        "\0".parent::class."\0".'visibilite' => [parent::class, 'visibilite', null, 16],
        'commentaires' => [parent::class, 'commentaires', null, 16],
        'contenu' => [parent::class, 'contenu', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateModification' => [parent::class, 'dateModification', null, 16],
        'idPost' => [parent::class, 'idPost', null, 16],
        'likes' => [parent::class, 'likes', null, 16],
        'nombreCommentaires' => [parent::class, 'nombreCommentaires', null, 16],
        'nombreLikes' => [parent::class, 'nombreLikes', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'typePost' => [parent::class, 'typePost', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'visibilite' => [parent::class, 'visibilite', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
