<?php

namespace Proxies\__CG__\App\Entity\reclamation;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ticket extends \App\Entity\reclamation\Ticket implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateFermeture' => [parent::class, 'dateFermeture', null, 16],
        "\0".parent::class."\0".'deadline' => [parent::class, 'deadline', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null, 16],
        "\0".parent::class."\0".'priorite' => [parent::class, 'priorite', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateFermeture' => [parent::class, 'dateFermeture', null, 16],
        'deadline' => [parent::class, 'deadline', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'messages' => [parent::class, 'messages', null, 16],
        'priorite' => [parent::class, 'priorite', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
