<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JckUD5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JckUD5_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JckUD5_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'investmentRepository' => ['privates', 'App\\Repository\\InvestissementobligationRepository', 'getInvestissementobligationRepositoryService', true],
            'obligationRepository' => ['privates', 'App\\Repository\\ObligationRepository', 'getObligationRepositoryService', true],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGeneratorService', 'getPdfGeneratorServiceService', true],
        ], [
            'investmentRepository' => 'App\\Repository\\InvestissementobligationRepository',
            'obligationRepository' => 'App\\Repository\\ObligationRepository',
            'pdfGenerator' => 'App\\Service\\PdfGeneratorService',
        ]);
    }
}
