<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T0ZvgmxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T0Zvgmx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ticket' => ['privates', '.errored..service_locator.T0Zvgmx.App\\Entity\\reclamation\\Ticket', NULL, 'Cannot autowire service ".service_locator.T0Zvgmx": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'ticket' => 'App\\Entity\\reclamation\\Ticket',
        ]);

        if (isset($container->privates['.service_locator.T0Zvgmx'])) {
            return $container->privates['.service_locator.T0Zvgmx'];
        }

        return $container->privates['.service_locator.T0Zvgmx'] = $instance;
    }
}
