<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BRGx3JNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BRGx3JN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectif' => ['privates', '.errored..service_locator.BRGx3JN.App\\Entity\\objective\\Objectif', NULL, 'Cannot autowire service ".service_locator.BRGx3JN": it needs an instance of "App\\Entity\\objective\\Objectif" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'objectif' => 'App\\Entity\\objective\\Objectif',
        ]);

        if (isset($container->privates['.service_locator.BRGx3JN'])) {
            return $container->privates['.service_locator.BRGx3JN'];
        }

        return $container->privates['.service_locator.BRGx3JN'] = $instance;
    }
}
