<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9nAU4CbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9nAU4Cb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService', true],
        ], [
            'entityManager' => '?',
            'repository' => 'App\\Repository\\WalletRepository',
        ]);

        if (isset($container->privates['.service_locator.9nAU4Cb'])) {
            return $container->privates['.service_locator.9nAU4Cb'];
        }

        return $container->privates['.service_locator.9nAU4Cb'] = $instance;
    }
}
