<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7dk4zOhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7dk4zOh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'investmentRepository' => ['privates', 'App\\Repository\\InvestissementobligationRepository', 'getInvestissementobligationRepositoryService', true],
            'obligation' => ['privates', '.errored..service_locator.7dk4zOh.App\\Entity\\Loan\\Obligation', NULL, 'Cannot autowire service ".service_locator.7dk4zOh": it needs an instance of "App\\Entity\\Loan\\Obligation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'investmentRepository' => 'App\\Repository\\InvestissementobligationRepository',
            'obligation' => 'App\\Entity\\Loan\\Obligation',
        ]);

        if (isset($container->privates['.service_locator.7dk4zOh'])) {
            return $container->privates['.service_locator.7dk4zOh'];
        }

        return $container->privates['.service_locator.7dk4zOh'] = $instance;
    }
}
