<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4L5dmlmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4L5dmlm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notificationService' => ['privates', 'App\\Service\\SimpleNotificationService', 'getSimpleNotificationServiceService', true],
        ], [
            'entityManager' => '?',
            'notificationService' => 'App\\Service\\SimpleNotificationService',
        ]);

        if (isset($container->privates['.service_locator.4L5dmlm'])) {
            return $container->privates['.service_locator.4L5dmlm'];
        }

        return $container->privates['.service_locator.4L5dmlm'] = $instance;
    }
}
