<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\advancedfeature\ChatbotController' shared autowired service.
     *
     * @return \App\Controller\advancedfeature\ChatbotController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'advancedfeature'.\DIRECTORY_SEPARATOR.'ChatbotController.php';

        $container->services['App\\Controller\\advancedfeature\\ChatbotController'] = $instance = new \App\Controller\advancedfeature\ChatbotController(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), \dirname(__DIR__, 4), $container->getEnv('OLLAMA_API_URL'));

        $instance->setContainer(($container->privates['.service_locator.BWRinXy'] ?? $container->load('get_ServiceLocator_BWRinXyService'))->withContext('App\\Controller\\advancedfeature\\ChatbotController', $container));

        return $instance;
    }
}
