<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroqSummaryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GroqSummaryService' shared autowired service.
     *
     * @return \App\Service\GroqSummaryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GroqSummaryService.php';

        return $container->privates['App\\Service\\GroqSummaryService'] = new \App\Service\GroqSummaryService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('GROQ_API_KEY'), $container->getEnv('GROQ_MODEL'));
    }
}
