<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvestissementobligationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\InvestissementobligationType' shared autowired service.
     *
     * @return \App\Form\InvestissementobligationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'InvestissementobligationType.php';

        return $container->privates['App\\Form\\InvestissementobligationType'] = new \App\Form\InvestissementobligationType(($container->privates['App\\Repository\\WalletRepository'] ?? $container->load('getWalletRepositoryService')), ($container->privates['App\\Repository\\ObligationRepository'] ?? $container->load('getObligationRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
