<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObligationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Loan\ObligationController' shared autowired service.
     *
     * @return \App\Controller\Loan\ObligationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Loan'.\DIRECTORY_SEPARATOR.'ObligationController.php';

        $container->services['App\\Controller\\Loan\\ObligationController'] = $instance = new \App\Controller\Loan\ObligationController(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('OLLAMA_API_URL'));

        $instance->setContainer(($container->privates['.service_locator.BWRinXy'] ?? $container->load('get_ServiceLocator_BWRinXyService'))->withContext('App\\Controller\\Loan\\ObligationController', $container));

        return $instance;
    }
}
