<?php

namespace ContainerP2NppJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Bundle\StatisticController' shared autowired service.
     *
     * @return \App\Controller\Bundle\StatisticController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Bundle'.\DIRECTORY_SEPARATOR.'StatisticController.php';

        $container->services['App\\Controller\\Bundle\\StatisticController'] = $instance = new \App\Controller\Bundle\StatisticController();

        $instance->setContainer(($container->privates['.service_locator.BWRinXy'] ?? $container->load('get_ServiceLocator_BWRinXyService'))->withContext('App\\Controller\\Bundle\\StatisticController', $container));

        return $instance;
    }
}
