<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EzKe0vEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EzKe0vE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EzKe0vE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'ticket' => ['privates', '.errored..service_locator.EzKe0vE.App\\Entity\\reclamation\\Ticket', NULL, 'Cannot autowire service ".service_locator.EzKe0vE": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'ticket' => 'App\\Entity\\reclamation\\Ticket',
        ]);
    }
}
