<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GylZskzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GylZskz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.GylZskz.App\\Entity\\reclamation\\Message', NULL, 'Cannot autowire service ".service_locator.GylZskz": it needs an instance of "App\\Entity\\reclamation\\Message" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'message' => 'App\\Entity\\reclamation\\Message',
        ]);

        if (isset($container->privates['.service_locator.GylZskz'])) {
            return $container->privates['.service_locator.GylZskz'];
        }

        return $container->privates['.service_locator.GylZskz'] = $instance;
    }
}
