<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VfFEsH_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VfFEsH.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'connection' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
            'contribution' => ['privates', '.errored..service_locator.VfFEsH..App\\Entity\\objective\\Contributiongoal', NULL, 'Cannot autowire service ".service_locator.VfFEsH.": it needs an instance of "App\\Entity\\objective\\Contributiongoal" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'connection' => '?',
            'contribution' => 'App\\Entity\\objective\\Contributiongoal',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.VfFEsH.'])) {
            return $container->privates['.service_locator.VfFEsH.'];
        }

        return $container->privates['.service_locator.VfFEsH.'] = $instance;
    }
}
