<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sw43tdhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sw43tdh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sw43tdh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classifier' => ['privates', 'App\\Service\\TicketPriorityClassifierService', 'getTicketPriorityClassifierServiceService', true],
        ], [
            'classifier' => 'App\\Service\\TicketPriorityClassifierService',
        ]);
    }
}
