<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LN5YPz_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lN5YPz.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lN5YPz.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groqSuggestionService' => ['privates', 'App\\Service\\GroqSuggestionService', 'getGroqSuggestionServiceService', true],
            'ticket' => ['privates', '.errored..service_locator.lN5YPz..App\\Entity\\reclamation\\Ticket', NULL, 'Cannot autowire service ".service_locator.lN5YPz.": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'groqSuggestionService' => 'App\\Service\\GroqSuggestionService',
            'ticket' => 'App\\Entity\\reclamation\\Ticket',
        ]);
    }
}
