<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_51kIyktService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.51kIykt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'obligationRepository' => ['privates', 'App\\Repository\\ObligationRepository', 'getObligationRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'obligationRepository' => 'App\\Repository\\ObligationRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.51kIykt'])) {
            return $container->privates['.service_locator.51kIykt'];
        }

        return $container->privates['.service_locator.51kIykt'] = $instance;
    }
}
