<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VuciIUIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vuciIUI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'walletRepository' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'entityManager' => '?',
            'validator' => '?',
            'walletRepository' => 'App\\Repository\\WalletRepository',
        ]);

        if (isset($container->privates['.service_locator.vuciIUI'])) {
            return $container->privates['.service_locator.vuciIUI'];
        }

        return $container->privates['.service_locator.vuciIUI'] = $instance;
    }
}
