<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\advancedfeature\AlertController' shared autowired service.
     *
     * @return \App\Controller\advancedfeature\AlertController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'advancedfeature'.\DIRECTORY_SEPARATOR.'AlertController.php';

        $container->services['App\\Controller\\advancedfeature\\AlertController'] = $instance = new \App\Controller\advancedfeature\AlertController();

        $instance->setContainer(($container->privates['.service_locator.99441U6'] ?? $container->load('get_ServiceLocator_99441U6Service'))->withContext('App\\Controller\\advancedfeature\\AlertController', $container));

        return $instance;
    }
}
