<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCloudinaryUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CloudinaryUploader' shared autowired service.
     *
     * @return \App\Service\CloudinaryUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CloudinaryUploader.php';

        return $container->privates['App\\Service\\CloudinaryUploader'] = new \App\Service\CloudinaryUploader($container->getEnv('CLOUDINARY_URL'));
    }
}
