<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinancialHealthServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FinancialHealthService' shared autowired service.
     *
     * @return \App\Service\FinancialHealthService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FinancialHealthService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\FinancialHealthService'])) {
            return $container->privates['App\\Service\\FinancialHealthService'];
        }

        $instance = new \App\Service\FinancialHealthService(($container->privates['App\\Repository\\WalletRepository'] ?? $container->load('getWalletRepositoryService')), ($container->privates['App\\Repository\\InvestissementobligationRepository'] ?? $container->load('getInvestissementobligationRepositoryService')), ($container->privates['App\\Repository\\ObligationRepository'] ?? $container->load('getObligationRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\FinancialHealthService'])) {
            return $container->privates['App\\Service\\FinancialHealthService'];
        }

        return $container->privates['App\\Service\\FinancialHealthService'] = $instance;
    }
}
