<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObligationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7dk4zOh.App\Entity\Loan\Obligation' shared service.
     *
     * @return \App\Entity\Loan\Obligation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7dk4zOh": it needs an instance of "App\\Entity\\Loan\\Obligation" but this type has been excluded in "config/services.yaml".');
    }
}
