<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Bundle\Statistic\StatisticService' shared autowired service.
     *
     * @return \App\Bundle\Statistic\StatisticService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Bundle'.\DIRECTORY_SEPARATOR.'Statistic'.\DIRECTORY_SEPARATOR.'StatisticService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Bundle\\Statistic\\StatisticService'])) {
            return $container->privates['App\\Bundle\\Statistic\\StatisticService'];
        }

        $instance = new \App\Bundle\Statistic\StatisticService(($container->privates['App\\Repository\\InvestissementobligationRepository'] ?? $container->load('getInvestissementobligationRepositoryService')), ($container->privates['App\\Repository\\ObligationRepository'] ?? $container->load('getObligationRepositoryService')), ($container->privates['App\\Repository\\WalletRepository'] ?? $container->load('getWalletRepositoryService')), $a);

        if (isset($container->privates['App\\Bundle\\Statistic\\StatisticService'])) {
            return $container->privates['App\\Bundle\\Statistic\\StatisticService'];
        }

        return $container->privates['App\\Bundle\\Statistic\\StatisticService'] = $instance;
    }
}
