<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\managment\StatsController' shared autowired service.
     *
     * @return \App\Controller\managment\StatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'managment'.\DIRECTORY_SEPARATOR.'StatsController.php';

        $container->services['App\\Controller\\managment\\StatsController'] = $instance = new \App\Controller\managment\StatsController();

        $instance->setContainer(($container->privates['.service_locator.99441U6'] ?? $container->load('get_ServiceLocator_99441U6Service'))->withContext('App\\Controller\\managment\\StatsController', $container));

        return $instance;
    }
}
