<?php

namespace ContainerJigBS7b;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicket5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T0Zvgmx.App\Entity\reclamation\Ticket' shared service.
     *
     * @return \App\Entity\reclamation\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T0Zvgmx": it needs an instance of "App\\Entity\\reclamation\\Ticket" but this type has been excluded in "config/services.yaml".');
    }
}
