services:
    _defaults:
        autowire: true
        autoconfigure: true
        # Supprime toute ligne comme : bind:
        #   $hasdataApiKey: '%env(HASDATA_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service pour Twelve Data
    App\Service\TwelveDataService:
        arguments:
            $apiKey: '%env(TWELVE_DATA_API_KEY)%'