<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFSAaV93\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFSAaV93/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFSAaV93.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFSAaV93\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFSAaV93\App_KernelDevDebugContainer([
    'container.build_hash' => 'FSAaV93',
    'container.build_id' => '25fab2bd',
    'container.build_time' => 1777744515,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFSAaV93');
