<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJigBS7b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJigBS7b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJigBS7b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJigBS7b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJigBS7b\App_KernelDevDebugContainer([
    'container.build_hash' => 'JigBS7b',
    'container.build_id' => 'd5819139',
    'container.build_time' => 1777463787,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJigBS7b');
